---
title: "Management Discussion and Analysis"
author: "John Karuitha"
date: "`r Sys.Date()`"
output:
  beamer_presentation: default
  slidy_presentation: default
  ioslides_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# **Background**

Management discussion and analysis (MD&A) section within a company's financial report analyzes the company's performance and financial condition from the viewpoint of top management.


# The analysis may also include the following discussion;

- Business overview including the legal, political, and economic environment.

- Results of operations.

- Liquidity and financial condition.

- Acquisitions.

# The MDA may also Include

- Restructuring activities.

- Pertinent Risks.

- Regulatory compliance.

# The MDA may also Include

- Future plans, such as goals and new projects planned by the management.

- Other relevant information like charges for impairments, accounting estimates and assumptions.


# Reporting Quality

- Ideally, analysts would always have access to financial reports that are based on sound financial reporting standards; 

  - The International Accounting Standards Board (IASB) 
  - The Financial Accounting Standards Board (FASB), 

# Reporting Quality

- Financial statements should be free from manipulation. 
- In practice, the quality of financial reports can vary greatly. - High-quality financial reporting provides information that is useful to analysts in assessing a company’s performance and prospects. 
- Low-quality financial reporting contains inaccurate, misleading, or incomplete information.


# Reporting Quality

- Lapses in financial reporting quality have given rise to high-profile scandals that resulted not only in investor losses but also in reduced confidence in the financial system. 

- Financial statement users who were able to accurately assess financial reporting quality were better positioned to avoid losses. 

- These lapses illustrate the challenges analysts face as well as the potential costs of failing to recognize practices that result in misleading or inaccurate financial reports. 

# Reporting Quality

- Examples of misreporting can provide an analyst with insight into various signals that may indicate poor-quality financial reports.



# Reporting Quality

- Financial reporting quality can be thought of as spanning a continuum from the highest (containing information that is relevant, correct, complete, and unbiased) to the lowest (containing information that is not just biased or incomplete but possibly pure fabrication).

# Reporting Quality

- Reporting quality, the focus of this reading, pertains to the information disclosed. High-quality reporting represents the economic reality of the company’s activities during the reporting period and the company’s financial condition at the end of the period.

# Reporting Quality

- Results quality (commonly referred to as earnings quality) pertains to the earnings and cash generated by the company’s actual economic activities and the resulting financial condition, relative to expectations of current and future financial performance. Quality earnings are regarded as being sustainable, providing a sound platform for forecasts.

# Reporting Quality

- An aspect of financial reporting quality is the degree to which accounting choices are conservative or aggressive. “Aggressive” typically refers to choices that aim to enhance the company’s reported performance and financial position by inflating the amount of revenues, earnings, and/or operating cash flow reported in the period; or by decreasing expenses for the period and/or the amount of debt reported on the balance sheet.

# Reporting Quality

- Conservatism in financial reports can result from either (1) accounting standards that specifically require a conservative treatment of a transaction or an event or (2) judgments made by managers when applying accounting standards that result in conservative results.

# Reporting Quality

- Managers may be motivated to issue less-than-high-quality financial reports in order to mask poor performance, to boost the stock price, to increase personal compensation, and/or to avoid violation of debt covenants.

# Reporting Quality

- Conditions that are conducive to the issuance of low-quality financial reports include a cultural environment that result in fewer or less transparent financial disclosures, book/tax conformity that shifts emphasis toward legal compliance and away from fair presentation, and limited capital markets regulation.

# Reporting Quality

- Mechanisms that discipline financial reporting quality include the free market and incentives for companies to minimize cost of capital, auditors, contract provisions specifically tailored to penalize misreporting, and enforcement by regulatory entities.

# Reporting Quality
- Pro forma earnings (also commonly referred to as non-GAAP or non-IFRS earnings) adjust earnings as reported on the income statement. Pro forma earnings that exclude negative items are a hallmark of aggressive presentation choices.

# Reporting Quality

- Companies are required to make additional disclosures when presenting any non-GAAP or non-IFRS metric.

- Managers’ considerable flexibility in choosing their companies’ accounting policies and in formulating estimates provides opportunities for aggressive accounting.

# Reporting Quality

- Examples of accounting choices that affect earnings and balance sheets include inventory cost flow assumptions, estimates of uncollectible accounts receivable, estimated realizability of deferred tax assets, depreciation method, estimated salvage value of depreciable assets, and estimated useful life of depreciable assets.

# Reporting Quality

- Cash from operations is a metric of interest to investors that can be enhanced by operating choices, such as stretching accounts payable, and potentially by classification choices.


# Some Techniques of that Result in Poor Quality Reporting

- Income Smoothing.
- Big bath accounting.
- Management Fraud.





